# Generated by Django 3.1.7 on 2021-03-31 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_disliked_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='acquaintance_state',
            field=models.CharField(choices=[('0', 'Not answered'), ('1', 'Not liked'), ('2', 'Both liked')], default='0', max_length=1),
        ),
    ]
